### ISSUE TITLE
redis_node_manager should start if no redis servers are available

### ISSUE THREAD

**Issue by eric** [ryanlecompte/redis_failover#29]
Here's a stack trace:

```
lib/redis_failover/version.rb:2: warning: already initialized constant VERSION
Mon Aug 13 05:29:22 UTC 2012 RedisFailover 46108 INFO: Redis Node Manager v0.8.9 starting (ruby 1.8.7 (2011-12-28 MBARI 8/0x6770 on patchlevel 357) [i686-darwin11.3.0], MBARI 0x6770, Ruby Enterprise Edition 2011.12)
Mon Aug 13 05:29:22 UTC 2012 RedisFailover 46108 INFO: Waiting to become master Node Manager ...
Mon Aug 13 05:29:22 UTC 2012 RedisFailover 46108 INFO: Acquired master Node Manager lock
lib/redis_failover/node_manager.rb:222:in `discover_nodes': RedisFailover::NoMasterError (RedisFailover::NoMasterError)
    from lib/redis_failover/runner.rb:14:in `join'
    from lib/redis_failover/runner.rb:14:in `run'
    from bin/redis_node_manager:6
    from bin/redis_node_manager:23:in `load'
    from bin/redis_node_manager:23
```

**Comment by ryanlecompte** [comment]
FIxed in 3566089a8045a8548dec8bd6e0b6a9c50accf48f
