### ISSUE TITLE
 Starting redis_node_manager connection timeouts 

### ISSUE THREAD

**Issue by lazzarouk** [ryanlecompte/redis_failover#75]
Hi,

 I was looking for a fail over package and found this package so I'm fairly  new to this. I have started to experiment with it and I had entered on the command line 

$ redis_node_manager -n localhost:6000,localhost:6001 -z localhost:7000,localhost:7001,localhost:7002 --with-chroot /tmp/

So after 30 seconds I would get this message continuously can you please help 

ERROR: ZK error while attempting to manage nodes: #<Zookeeper::Exceptions::ContinuationTimeoutError: response for meth: :exists, args: [0, "/opt/", nil, nil], not received within 30 seconds>

**Comment by arohter** [comment]
Impossible to tell without the full exception trace.

**Comment by lazzarouk** [comment]
Thank you for responding back. This is the command I had entered
$ redis_node_manager -n localhost:6000,localhost:6001 -z localhost:7000,localhost:7001,localhost:7002

2014-05-12 22:18:32 UTC RedisFailover 19605 INFO: Redis Node Manager v1.0.2 starting (ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux])
2014-05-12 22:19:22 UTC RedisFailover 19605 ERROR: ZK error while attempting to manage nodes: #<Zookeeper::Exceptions::ContinuationTimeoutError: response for meth: :exists, args: [0, "/tmp/redis_nodes", nil, nil], not received within 30 seconds>

014-05-12 22:20:17 UTC RedisFailover 19605 ERROR: ZK error while attempting to manage nodes: #<Zookeeper::Exceptions::ContinuationTimeoutError: response for meth: :exists, args: [0, "/tmp/redis_nodes", nil, nil], not received within 30 seconds>

=====>> I Have interrupted it "CTRL-C" and here is the stack log
^Clog writing failed. can't be called from trap context
/home/lazzarouk/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:185:in `lock': can't be called from trap context (ThreadError)
    from /home/lazzarouk/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:185:in`mon_enter'
    from /home/lazzarouk/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:209:in `mon_synchronize'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/redis_failover-1.0.2/lib/redis_failover/node_manager.rb:99:in`shutdown'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/redis_failover-1.0.2/lib/redis_failover/runner.rb:21:in `block (2 levels) in trap_signals'
    from /home/lazzarouk/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:110:in`call'
    from /home/lazzarouk/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:110:in `sleep'
    from /home/lazzarouk/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:110:in`wait'
    from /home/lazzarouk/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:110:in `wait'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zookeeper-1.4.8/lib/zookeeper/continuation.rb:113:in`block in value'
    from /home/lazzarouk/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zookeeper-1.4.8/lib/zookeeper/continuation.rb:107:in`value'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zookeeper-1.4.8/ext/c_zookeeper.rb:231:in `submit_and_block'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zookeeper-1.4.8/ext/c_zookeeper.rb:40:in`exists'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zookeeper-1.4.8/lib/zookeeper/client_methods.rb:82:in `stat'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zk-1.7.5/lib/zk/client/base.rb:1055:in`call_and_check_rc'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zk-1.7.5/lib/zk/client/threaded.rb:579:in `call_and_check_rc'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zk-1.7.5/lib/zk/client/base.rb:623:in`block in stat'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zk-1.7.5/lib/zk/event_handler.rb:282:in `setup_watcher!'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zk-1.7.5/lib/zk/client/base.rb:1100:in`setup_watcher!'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zk-1.7.5/lib/zk/client/base.rb:622:in `stat'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/zk-1.7.5/lib/zk/client/base.rb:648:in`exists?'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/redis_failover-1.0.2/lib/redis_failover/node_manager.rb:389:in `create_path'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/redis_failover-1.0.2/lib/redis_failover/node_manager.rb:119:in`setup_zk'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/redis_failover-1.0.2/lib/redis_failover/node_manager.rb:57:in `start'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/redis_failover-1.0.2/lib/redis_failover/runner.rb:13:in`run'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/gems/redis_failover-1.0.2/bin/redis_node_manager:6:in `<top (required)>'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/bin/redis_node_manager:23:in`load'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/bin/redis_node_manager:23:in `<main>'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in`eval'
    from /home/lazzarouk/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by arohter** [comment]
The exception when you ctrl-c is this ruby 2.x issue - https://github.com/ryanlecompte/redis_failover/issues/62 - but I don't understand why there's no exception trace printed (just "#" ?) for the zk failure: https://github.com/ryanlecompte/redis_failover/blob/v1.0.2/lib/redis_failover/node_manager.rb#L61

HOWEVER, I'd start by updating to a modern `zk` gem version first; `zk-1.7.5` is extremely old.
You should be running zk _1.9.4_ (http://rubygems.org/gems/zk) and zookeeper 1.4.8 (http://rubygems.org/gems/zookeeper).
